### ISSUE TITLE
Close the issue

### ISSUE THREAD

**Issue by matthieugomez** [christopher-dG/tag-bot#2]
This is a great bot! Thanks for doing this.  Do you think tag-bot could also close the issue initially opened with `@JuliaRegistrator register()`?

**Comment by christopher-dG** [comment]
I'd rather not, I don't really want to make assumptions on how Registrator is being used. If you don't want to deal with hanging issues you can use commit comments instead ([example](https://github.com/JuliaIO/LibSerialPort.jl/commit/a4d1e5575837e21c3875d90bab707b92df0810d9#commitcomment-33265645)).

**Comment by matthieugomez** [comment]
I see. Thanks!
