### ISSUE TITLE
Tag ignored second (correcty) register() call

### ISSUE THREAD

**Issue by dlfivefifty** [christopher-dG/tag-bot#3]
This tag

https://github.com/JuliaApproximation/DomainSets.jl/releases/tag/v0.0.2

was put on the wrong commit. The actual release 

https://github.com/JuliaRegistries/General/pull/220

was attached to a second call to register() associated with a different commit.

**Comment by christopher-dG** [comment]
This is more of a Registrator bug, all TagBot does is read the commit hash that's mentioned in the PR body. Registrator however does not update the hash when it updates itself.

**Comment by dlfivefifty** [comment]
OK I'll create a cross-ref issue.

**Comment by christopher-dG** [comment]
Looks like this will no longer be an issue as soon as the new Registrator version is deployed.
